name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ansh-testing-pipeline
  pull_request:
    branches:
      - main
      - ansh-testing-pipeline

permissions:
  contents: write

env:
  NEXT_PUBLIC_SPOONACULAR_API_KEY: ${{ secrets.NEXT_PUBLIC_SPOONACULAR_API_KEY }}
  GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
  NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean up Git configurations
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git submodule foreach --recursive 'git config --local --unset-all http.https://github.com/.extraheader || true'
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install

  run-tests:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --no-cache
      - name: Run Unit Tests
        run: bun run test tests/unit --coverage
      - name: Run Integration Tests
        run: bun run test tests/integration
      - name: Install Playwright
        run: bun add playwright
      # - name: Run E2E Tests
      #   run: bun run playwright test

  build:
      needs: run-tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest
        - name: Install dependencies
          run: bun install --no-cache
        - name: Add node_modules/.bin to PATH
          run: echo 'PATH=$(pwd)/node_modules/.bin:$PATH' >> $GITHUB_ENV
        - name: Build project
          run: bun run build --verbose

