name: Bun CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  NEXT_PUBLIC_SPOONACULAR_API_KEY: ${{ secrets.NEXT_PUBLIC_SPOONACULAR_API_KEY }}
  GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clean up Git configurations
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
        git submodule foreach --recursive 'git config --local --unset-all http.https://github.com/.extraheader || true'

    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun run test

    - name: Build project
      run: bun run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clean up Git configurations
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
        git submodule foreach --recursive 'git config --local --unset-all http.https://github.com/.extraheader || true'

    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Deploy to Netlify
      if: success() && github.ref == 'refs/heads/main'
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        npm install -g netlify-cli
        netlify deploy --prod
