<<<<<<< HEAD
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ansh-testing-pipeline
  pull_request:
    branches:
      - main
      - ansh-testing-pipeline

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: install
    env:
      GOOGLE_CALENDAR_API_KEY: ${{ secrets.API_KEY_GOOGLE_CALENDAR }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXT_PUBLIC_SPOONACULAR_API_KEY: ${{ secrets.NEXT_PUBLIC_SPOONACULAR_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: bun run vitest tests/unit --coverage

  run-integration-tests:
    runs-on: ubuntu-latest
    needs: install
    env:
      GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXT_PUBLIC_SPOONACULAR_API_KEY: ${{ secrets.NEXT_PUBLIC_SPOONACULAR_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Run integration tests
        run: bun run vitest tests/integration

  run-e2e-tests:
    runs-on: ubuntu-latest
    needs: install
    env:
      GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXT_PUBLIC_SPOONACULAR_API_KEY: ${{ secrets.NEXT_PUBLIC_SPOONACULAR_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Playwright
        run: bun add playwright
      - name: Run E2E tests
        run: bun run playwright test

  deploy:
    needs: [run-unit-tests, run-integration-tests, run-e2e-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
=======
name: Bun CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

env:
  NEXT_PUBLIC_SPOONACULAR_API_KEY: ${{ secrets.NEXT_PUBLIC_SPOONACULAR_API_KEY }}
  GOOGLE_CALENDAR_API_KEY: ${{ secrets.GOOGLE_CALENDAR_API_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clean up Git configurations
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
        git submodule foreach --recursive 'git config --local --unset-all http.https://github.com/.extraheader || true'

    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun run test

    - name: Build project
      run: bun run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Clean up Git configurations
      run: |
        git config --local --unset-all http.https://github.com/.extraheader || true
        git submodule foreach --recursive 'git config --local --unset-all http.https://github.com/.extraheader || true'

    - name: Use Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Deploy to Netlify
      if: success() && github.ref == 'refs/heads/main'
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        npm install -g netlify-cli
        netlify deploy --prod
>>>>>>> c44443251ff99b215a309974030a8d55c4d74fd5
